import Colours1 from "../../assets/BlueProducts/3.jpg";
import Colours2 from "../../assets/RedProducts/11.jpg";
import Colours3 from "../../assets/GreenProducts/2.jpg";
import Colours4 from "../../assets/BlueProducts/4.jpg";
import Colours5 from "../../assets/BlueProducts/5.jpg";
import Colours6 from "../../assets/ProductsImage/dress6.jpg";
import Colours7 from "../../assets/ProductsImage/dress7.jpg";
import Colours8 from "../../assets/ProductsImage/il_794xN.4306523229_ori8.webp";
import Fabaric1 from "../../assets/RecycledAssets/AKKA FAKE FISG RED CANVAS.jpg";
import Fabaric2 from "../../assets/LinenAssets/LINE/LINE.jpg";
import Fabaric3 from "../../assets/OCassets/FLOWER SHAL BEIGE CANVAS.jpg";
import Fabaric4 from "../../assets/OCassets/all shalimar canvas.jpg";
import Fabaric5 from "../../assets/LinenAssets/LINE/olpure5.jpg";
import Fabaric6 from "../../assets/ProductsImage/il_794xN.5185197427_16jr.avif";
import Patterns1 from "../../assets/AviaryAssets/FRIDA BLUE FLOWER CANVAS.jpg";
import Patterns2 from "../../assets/FloralAssets/big.jpg";
import Patterns3 from "../../assets/AviaryAssets/TOUCAN GREEN CANVAS.jpg";
import Patterns4 from "../../assets/AviaryAssets/bird.jpg";
import Patterns5 from "../../assets/ProductsImage/il_794xN.1131388500_qp84.avif";
import Patterns6 from "../../assets/ProductsImage/il_794xN.5204058218_10nu.webp";
import Sign1 from "../../assets/ProductsImage/sign1.webp";
import Sign2 from "../../assets/ProductsImage/sign2.webp";
import Sign3 from "../../assets/ProductsImage/sign3.webp";
import Sign4 from "../../assets/ProductsImage/1.webp"; 
import Sign5 from "../../assets/ProductsImage/2.avif";
import Sign6 from "../../assets/ProductsImage/3.avif";
const ProductsImage = [
  { name: "SANTE Midi", 
  Image: Sign4,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "26", 
},
{ name: "OU Midi", 
  Image: Sign5,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "27", 
},
{ name: "OS Midi", 
  Image: Sign6,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "28", 
},
  { name: "Robe Midi", 
  Image: Sign1,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "14", 
},
{ name: "Kaftan Long Chudi", 
  Image: Sign2,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "15",  
},
{ name: "Cotton skirt", 
  Image: Sign3,
  description: "Product multicolored Kimono jacket with large collar and one size animal design",
  producttype: "Signature",
  id: "16", 
},
  {
    description: "Reversible multicolored Kimono jacket with large collar and one size animal design",
    name: "OC DENIM",
    Image: Colours1,
    price: "2116.00",
    producttype: "Colours",
    offerprice: "",
    id: "1",
  },
  {
    description: "SHORT fleece JACKET Women's jacket in green and MULTICOLOR cotton patchwork Lined jacket buttoned on the front Women's mid-season jacket",
    name: "OC POPLIN",
    Image: Colours2,
    price: "2343.00",
    producttype: "Colours",
    offerprice: "",
    id: "2",
  },
  {
    description: "Handmade brown Jacket and MULTICOLOR cotton patchwork cotton curtain with Lined jacket buttoned on the front Women's mid-season jacket and one size animal design",
    name: "OC TWILL",
    Image: Fabaric1,
    price: "1700.00",
    producttype: "Fabric",
    offerprice: "",
    id: "3",
  },
  {
    description: "Handmade blue and MULTICOLOR cotton patchwork cotton curtain with Lined jacket buttoned on the front Women's mid-season jacket and one size animal design",
    name: "OC MUSLIN",
    Image: Fabaric2,
    price: "1700.00",
    producttype: "Fabric",
    offerprice: "",
    id: "4",
  },
  {
    description: "PATCHWORK CURTAIN black and multicolored custom curtain cotton curtain with solid color lining matching the cotton curtain with patchwork and one size animal design",
    name: "PS HABOTAI",
    Image: Fabaric3,
    price: "1209.00",
    producttype: "Fabric",
    offerprice: "",
    id: "5",
  },
  {
    description: "Long tunic, reversible blue and white dress with flower design and Lined cotton curtain with jacket buttoned on the front Women's mid-season jacket and one size animal design ",
    name: "BINDU FLOWER",
    Image: Colours3,
    price: "1512.00",
    producttype: "Colours",
    offerprice: "",
    id: "6",
  },
  {
    description: "Curtain Wall hanging Custom handmade multicolored cotton patchwork curtain, and front Women's cotton curtain with mid-season jacket and one size animal design   ",
    name: "CANVAS RPET",
    Image: Patterns1,
    price: "1210.00",
    producttype: "Patterns",
    offerprice: "",
    id: "7",
  },
  {
    description: "PATCHWORK CURTAIN black and multicolored custom curtain cotton curtain with solid color lining matching cotton curtain with the patchwork and one size animal design    ",
    name: "RIPSTOP",
    Image: Patterns2,
    price: " 1210.00",
    producttype: "Patterns",
    offerprice: "",
    id: "8",
  },
  {
    description: "Door or window top garland made of boiled wool beads and small cotton curtain with wooden pot with solid color lining matching the patchwork and one size animal design  ",
    name: "OC VOILE",
    Image: Patterns3,
    price: "1796.00",
    producttype: "Patterns",
    offerprice: "",
    id: "9",
  },
  {
    description: "Garland fabric at the top of the door or window with small hearts and stars in cotton curtain with multicolored deco multicolor decoration items  and one size animal design    ",
    name: "OC SATEEN",
    Image: Patterns4,
    price: " 1890.00",
    producttype: "Patterns",
    offerprice: "",
    id: "10",
  },
  {
    description: "Affiche numérique - Art at the top of the door or window cotton curtain with in multicolored with deco multicolor decoration items  and one size animal decoration design",
    name: "OC DUCK",
    Image: Patterns5,
    price: " 350.00",
    producttype: "Patterns",
    offerprice: "",
    id: "11",
  },
  {
    description: "Asymmetrical Mirror, Irregular Mirror, Wavy Mirror, Mirror Wall cotton curtain with Decor on Tempered Glass, Entryway Hallway Mirror, Mirror for Bathroom",
    name: "OL-OC",
    Image: Patterns6,
    price: " 11350.00",
    producttype: "Patterns",
    offerprice: "",
    id: "11",
  },
  {
    description: "Plain Fabric with soft cotton plain light red colored cotton curtain with multicolored cotton patchwork curtain, and front Women's mid-season jacket and one size animal design  ",
    name: "OC-HEMP",
    Image: Fabaric4,
    price: "850.00",
    producttype: "Fabric",
    offerprice: "",
    id: "12",
  },
  {
    description: "Long summer dress with or without sleeves in white cotton curtain with cotton printed in floral and bird design size in request  and front Women's jacket and one animal design  ",
    name: "OC D.GAUZE",
    Image: Colours4,
    price: "1662.00",
    producttype: "Clothing",
    offerprice: "65.00",
    id: "13",
  },
  // {
  //   name: "Shirts",
  //   Image: shirts,
  //   price: " 79.00",
  //   producttype: "Clothing",
  //   offerprice: "",
  //   id: "16",
  // },
  {
    description: "Handmade Dress Material for women batik printed cotton curtain with clothing items for women stars in multicolored deco multicolor decoration items  and one size animal design",
    name: "BIG FLOWER",
    Image: Fabaric6,
    price: "5.00",
    producttype: "Fabric",
    offerprice: "",
    id: "17",
  },
  {
    description: "Dress Material Handworked Fabric with solid color cotton curtain with lining matching the patchwork and bird design size in request  and front Women's jacket one animal design ",
    name: "TOUCAN",
    Image: Fabaric5,
    price: "355.00",
    producttype: "Fabric",
    offerprice: "",
    id: "18",
  },
  // {
  //   name: "Sweater",
  //   Image: Sweater,
  //   price: " 79.00",
  //   producttype: "Clothing",
  //   offerprice: "89.00",
  //   id: "18",
  // },
  {
    description: "Long summer dress with or without sleeves in cotton curtain with pink cotton printed paisley flowers flared  matching scarf and front Women's jacket animal design ",
    name: "PATCHWORK",
    Image: Colours5,
    price: "2078.00",
    producttype: "Patterns",
    offerprice: "",
    id: "19",
  },
  {
    description: "SHORT fleece JACKET Women's jacket in green and cotton curtain with MULTICOLOR cotton patchwork buttoned flared cut with matching scarf animal design",
    name: "ILLUSION",
    Image: Colours6,
    price: "2343.00",
    producttype: "Patterns",
    offerprice: "",
    id: "22",
  },
  {
    description: "SHORT fleece JACKET Women's jacket in green and MULTICOLOR cotton patchwork Lined jacket buttoned flared cut with matching scarf and front Women's jacket",
    name: "MODAL",
    Image: Colours7,
    price: "2343.00",
    producttype: "Colours",
    offerprice: "",
    id: "22",
  },
  {
    description: "Summer dress with or in pink cotton and printed paisley and flowers flared cut with Lined MULTICOLOR cotton patchwork buttoned flared cut with matching scarf and front Women's jacket",
    name: "OL PURE",
    Image: Colours8,
    price: "3663.00",
    producttype: "Colours",
    offerprice: "",
    id: "23",
  },
  {
    description: "KIMONO JACKET cotton hand block  printed paisley and flowers flared cut with Lined cotton patchwork buttoned flared cut with matching scarf and front Women's jacket",
    name: "OL-OC",
    Image: Colours1,
    price: "2663.00",
    producttype: "Colours",
    offerprice: "",
    id: "24",
  },
  {
    description: "KIMONO JACKET cotton hand block  printed paisley and flowers flared cut with Lined cotton patchwork buttoned flared cut with matching scarf and front Women's jacket",
    name: "OC-OL",
    Image: Colours3,
    price: "2663.00",
    producttype: "Colours",
    offerprice: "",
    id: "24",
  },
  {
    description: "Handmade brown Jacket and MULTICOLOR cotton patchwork Lined jacket buttoned and flowers on the front Women's mid-season jacket and one size animal design",
    name: "PS CREPE",
    Image: Fabaric1,
    price: "1700.00",
    producttype: "Fabric",
    offerprice: "",
    id: "25",
  },
  {
    description: "Handmade brown Jacket and MULTICOLOR cotton patchwork Lined jacket buttoned and flowers on the front Women's mid-season jacket and one size animal design",
    name: "OC PS",
    Image: Fabaric1,
    price: "1700.00",
    producttype: "Fabric",
    offerprice: "",
    id: "26",
  },
];
export default ProductsImage;
